my_string = input("Введите словосочетание: ")
print(len(my_string))
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(" ", ""))
print(my_string[:1])
print(my_string[1])
